### ISSUE TITLE
ui changes in license page 

### ISSUE THREAD

**Issue by KajalKushwahaDeveloper** [KajalKushwahaDeveloper/react_app#66]

**Comment by SaurabhShrestha87** [comment]
@KajalKushwahaDeveloper  What is this issue for??
Give a brief at the issue comments for clearity.

**Comment by SaurabhShrestha87** [comment]
@KajalKushwahaDeveloper @abhishekdiwedi6395 re-open with issue's briefing for future proofing completed issues and fixed bugs.
